### ISSUE TITLE
Improve slack messages

### ISSUE THREAD

**Issue by k1-hedayati** [bitnami-labs/kubewatch#80]
Hello there,
I've installed kubewatch on my cluster and enabled slack integration on it, here is sample messages that I receive:
```
kubewatch
A  in namespace  has been :

kubewatch
A pod in namespace gitlab has been created: runner-e34aa186-project-62-concurrent-0vchfv
kubewat 
A pod in namespace gitlab has been created: runner-e34aa186-project-62-concurrent-0vchfv
kubewatch
A pod in namespace gitlab has been created: runner-e34aa186-project-62-concurrent-0vchfv
```
There is an incomplete message about namespace and three duplicate messages which I guess they seem duplicate because they don't have enough information.
The other issue is in slack notification I see "message undefined" and "(message missing text)" and leave me no option other and checking channel to see notification content.

**Comment by ngtuna** [comment]
hi @k1-hedayati , thanks for the report. Which kubewatch version are you trying ?

**Comment by k1-hedayati** [comment]
I'm using v0.0.3

**Comment by ngtuna** [comment]
@k1-hedayati Thanks. The kubewatch controller has been improved a lot to adapt new client-go from the last release v0.0.3 so I suggest you try to [build kubewatch](https://github.com/bitnami-labs/kubewatch#building) from the latest code. v0.0.3 is probably flaky a bit. We should definitely release a new version for that reason. I will ping you in next few days once I can trigger the new release. Please stay tuned :-)

**Comment by k1-hedayati** [comment]
Thank you @ngtuna, so I'm waiting for a new release

**Comment by tylerauerbeck** [comment]
@ngtuna I'm noticing the same things that @k1-hedayati is mentioning even in the new builds. This was also briefly brought up as part of #77. To test this out, I've built kubewatch locally with `make build`

Once the build completes successfully, I then configure kubewatch to watch something simple (namespaces) : `./kubewatch config resource --ns` and then config slack to publish to my channel: `./kubewatch config slack -c my-channel -t my-token-123`

Once that's configured, I then kick off kubewatch: `, which generates the startup output in the terminal that we would expect for all of the existing namespaces in the cluster: 

```
INFO[0000] Starting kubewatch controller                 pkg=kubewatch-namespace
INFO[0000] Processing add to namespace: kube-public      pkg=kubewatch-namespace
INFO[0000] Processing add to namespace: default          pkg=kubewatch-namespace
INFO[0000] Processing add to namespace: kube-system      pkg=kubewatch-namespace
INFO[0000] Kubewatch controller synced and ready         pkg=kubewatch-namespace
2018/02/11 22:32:18 Message successfully sent to channel C8RJ85KHP at 1518406338.000112
2018/02/11 22:32:18 Message successfully sent to channel C8RJ85KHP at 1518406338.000147
2018/02/11 22:32:19 Message successfully sent to channel C8RJ85KHP at 1518406339.000002
```

There we see what we would expect. Three existing namespaces, three notifications sent to slack saying that a namespace was created (because they already exist. We then see the following in slack:

```
kubewatch
A namespace in namespace  has been created: kube-public
kubewatch
A namespace in namespace  has been created: default
kubewatch
A namespace in namespace  has been created: kube-system
```

So up to this point, everything is working as expected. But lets try creating a new namespace:
`kubectl create namespace kw-testing`

This works as expected, with the following output from `kubectl`:

```
kubectl create namespace kw-testing
namespace "kw-testing" created
```

Output from `kubewatch` terminal:
```
INFO[0449] Processing add to namespace: kw-testing       pkg=kubewatch-namespace
2018/02/11 22:39:47 Message successfully sent to channel C8RJ85KHP at 1518406787.000108
```

Output from slack:

```
kubewatch
A namespace in namespace  has been created: kw-testing
```

Alright, so up to this point, everything is still working as expected. No strange messages from slack saying that anything is missing. Everything appearing appropriately in the terminal. Messages saying what we expect them to in slack. So creation of objects seem to be good to go with the current master branch. So let's check out another action, updating an object.

Since we're dealing with namespaces, not too much to update. So we'll just apply a label to the namespace. We can do that with the following: `kubectl label namespace kw-testing testing=true`

This work as expected. Output from `kubectl`:
```
kubectl label namespace kw-testing testing=true
namespace "kw-testing" labeled
```

Output from `kubewatch` terminal:
```
INFO[3923] Processing update to namespace: kw-testing    pkg=kubewatch-namespace
2018/02/12 00:26:39 Message successfully sent to channel C8RJ85KHP at 1518413199.000151
```

So far so good.

Output from slack channel:
```
kubewatch
A namespace in namespace  has been created: kw-testing
```

Alright. Well that's unexpected. So at the terminal logging level, we're good. But that's because that logging is being done inside of the informer.AddEventHandler functions (https://github.com/bitnami-labs/kubewatch/commit/f0150e67cfc6a9db2756a66a0ab591092e82d677#222). I think the problem comes from how the eventhandler is being thrown inside of the processItem function (https://github.com/bitnami-labs/kubewatch/commit/f0150e67cfc6a9db2756a66a0ab591092e82d677#316). It looks like it either says -- this things exists, we'll throw `c.eventHandler.ObjectCreated` or something doesn't exist `c.eventHandler.ObjectDeleted`. There's never anything that attempts to figure out if something already existed and is just being updated to throw `c.eventHandler.ObjectUpdated`.

So I _believe_ that's what's causing the issue with the slack event handler. I could definitely be wrong, but would be interested in some others input on this.

Now the last action that we need to check out is the delete. This offers up some interesting output as a few folks have mentioned up to this point.

To kick this off, we'll delete our namespace with `kubectl`:
```
kubectl delete namespace kw-testing
namespace "kw-testing" deleted
```

We then take a look at the logging of the `kubewatch` terminal:
```
INFO[8020] Processing update to namespace: kw-testing    pkg=kubewatch-namespace
INFO[8020] Processing delete to namespace: kw-testing    pkg=kubewatch-namespace
2018/02/12 01:34:55 Message successfully sent to channel C8RJ85KHP at 1518417295.000173
2018/02/12 01:34:56 Message successfully sent to channel C8RJ85KHP at 1518417296.000001
```

That seems to be _mostly_ what we would expect. `kubewatch` picks translates a delete as an update first, and then a delete is triggered. That seems to make sense, but might be something worth investigating and cleaning up later. No harm at this point though.

Things look more interesting in slack though:
```
kubewatch
A namespace in namespace  has been created: kw-testing
kubewatch
A namespace in namespace  has been created: kw-testing
kubewatch
A  in namespace  has been :
```

So this isn't what we would expect to see at all. So we see two messages saying something has been created. This seems to line up with what we saw above with the update action. It thinks anything that isn't a delete is a create. Since we saw an update occur on the `kubewatch` terminal output, we can expect to see that same type of output in slack. However while we saw one update action in the terminal, we see what would look to be two happening in slack. We also saw one delete happen in the terminal. That kind of matches up and we see one message that isn't a created happen in slack. However the message is essentially useless because we don't actually have any information on the action that's occurring or the object that it's occurring to. It's basically just a blank message and the only real reason we can kind of line this up is because we see what's happening in the terminal. So at best, this is our assumption as to what's happening. At worst, we don't really know because nothing is really being returned appropriately.

So given that, I think there's some work to be done.

- [ ] develop a better way to trigger event handlers
- [ ] better message handling abilities (handle missing values)

For item one, my initial thought is to create and return a variable that contains the expected action (`created`,`deleted`,`updated`) based upon the `informer.addEventHandler` action that gets thrown (i.e. if `AddFunc` is triggered, then the variable returned would have the value `created`). We could then take that variable that is returned and give the `Controller` struct that is returned a property to hold that (`actionType` ?). I'm sure there are some better (perhaps cleaner) ways to do this, so I'm definitely open to hearing some other opinions.

For item two, we should just check all values that are being used as part of the message being returned for null or empty values. We should then just set those properties that meet that null/empty check to something like `N/A` or `empty`.

It should also be noted that I didn't see part of the issue that @k1-hedayati saw where slack would say that a message has a missing property. Maybe this is resolved with the new updates that have been made? @k1-hedayati if you see this after the new release update us here and we can take a further look. It may just be that this doesn't occur when watching the namespace object.

Sorry for the long winded post. Just thought it would be useful to get this all down in one issue. If any other information would be useful, please let me know.

**Comment by aananthraj** [comment]
@tylerauerbeck , It was a detailed explanation 👍 , I would like to add my thoughts here.

> create and return a variable that contains the expected action (created,deleted,updated) based upon the informer.addEventHandler action that gets thrown (i.e. if AddFunc is triggered, then the variable returned would have the value created). 

This is certainly needed following reasons.
- The key which is enqueued doesnot contain any information about its origin. i,e. its EventHandler function. This blocks us from classifying the events during consumption. 
https://github.com/bitnami-labs/kubewatch/blob/4d389a8f422dc950c7c9e7d37487ebb4b4d78ac4/pkg/controller/controller.go#L266-L271
- The consumer `processNextItem()` checks only the existence of a key in the informer store and creates alerts. so ObjectUpdated() in the queue are received as ObjectCreated().
https://github.com/bitnami-labs/kubewatch/blob/4d389a8f422dc950c7c9e7d37487ebb4b4d78ac4/pkg/controller/controller.go#L364-L370
 - During deletion, DeletionTimestamp and STATUS of the k8s object is updated. Informer initiates a valid UpdateFunc() event but it results in ObjectCreated() false alert, due to the issue discussed in the previous step. 
 - Upon Successful deletion of the object in the cluster, informer initiates a `DeleteFunc` and  `DeletionHandlingMetaNamespaceKeyFunc` used, returns only the name of the deleted object and not the metadata. 
https://github.com/bitnami-labs/kubewatch/blob/4d389a8f422dc950c7c9e7d37487ebb4b4d78ac4/pkg/controller/controller.go#L280-L281
This result in a nil Event, with all data as nil string "" and an false alert.
   ```
	A  in namespace  has been :
   ```

so there is a need for returning `key`, `eventType`, `resourceType` from informer.addEventHandler actions. using the following data type in the queue, could solve the problem.
```
// Event indicate the informerEvent
type  Event  struct {
	key 		string
	eventType 	string
	resourceType 	string
}
...
func  newResourceController(client kubernetes.Interface, eventHandler handlers.Handler, informer cache.SharedIndexInformer, resourceType string) *Controller {
	queue  := workqueue.NewRateLimitingQueue(workqueue.DefaultControllerRateLimiter())
	var  newEvent Event
	var  err  error
	informer.AddEventHandler(cache.ResourceEventHandlerFuncs{
		AddFunc: func(obj interface{}) {
		    newEvent.key, err  = cache.MetaNamespaceKeyFunc(obj)
		    newEvent.eventType  =  "create"
		    newEvent.resourceType  = resourceType
		    logrus.WithField("pkg", "kubewatch-"+resourceType).Infof("Processing add to %v: %s", resourceType, newEvent.key)
		   if err ==  nil {
		      queue.Add(newEvent)
		  }
                },
...
func (c *Controller) processItem(newEvent Event) error {
        ...
	switch newEvent.eventType {
	case  "create":
		if objectMeta.CreationTimestamp.Sub(serverStartTime).Seconds() >  0 {
			c.eventHandler.ObjectCreated(obj)
			return  nil
	         }
        ...
	case  "delete":
		// Create a variable of event.Event type
                 kbEvent  := event.Event{
			Kind: newEvent.resourceType,
			Name: newEvent.key,
		}
                 // handle event.Event type in the handler
		c.eventHandler.ObjectDeleted(kbEvent)
		return  nil
	}
return  nil
}
```

**Comment by tylerauerbeck** [comment]
@aananthraj So I've got most of this working. I'm just having an issue capturing the kbEvent inside of `event.go`. I tried adding the following:

```
} else if Event, ok := obj.(*Event); ok {
	...
}
```

I've tried a few different iterations of this, but can't seem to capture the right type. Any thoughts?

**Comment by tylerauerbeck** [comment]
@k1-hedayati We just merged a change from @aananthraj that should address the issues that you're seeing here. Go ahead and pull the master branch and let us know if you are still seeing issues.

**Comment by k1-hedayati** [comment]
@tylerauerbeck @aananthraj Thank you guys, is it possible to test the changes without going through building kubewatch?

**Comment by tylerauerbeck** [comment]
I won't say it's not possible, but I don't believe it would be easy or straight forward.

**Comment by tylerauerbeck** [comment]
@k1-hedayati I'm going to go ahead and close this issue since it looks like the latest commits have cleaned this up. If you continue to see issues, feel free to reopen this.
